sudo: false
language: node_js
node_js:
- '0.10'
before_script:
- export IRC_ENV=integration
script:
- npm test
after_script:
- npm run coverage
- npm run coveralls
env:
  global:
    secure: SP4q/4GDPUKkyZk3UNnas3qibouwaD/4uaumwIXlJEGr2ALfFUjUwVu1Q+enTjVbF2AmgE2w2FjarpPWaWqIHwY16TPuZ4iAajayJIZeg2lJzFBXCQhK3B8997pFqYeXWyoWEamhEa/4u2MDuGQSn0KuswxEQFYFG3W6V538PrQ=
